services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=polardb_catalog'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '54323:5432'
