spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:54323/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
polar:
  greeting: Welcome to the local book catalog
management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    web: debug
    sql: debug
